version: '3'

services:

  db:
    build:
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306"
    networks:
      - node-network

  app:
    build:
      context: ./node
    tty: true
    command: "node index.js"
    volumes:
      - ./node:/usr/src/app
    container_name: app
    ports:
      - "3000:3000"
    networks:
      - node-network
    depends_on:
      - db
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge